# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.2-fpm
pipelines:
  default:
    - step:
        caches:
          - composer
          - node
        script:
          - apt-get update && apt-get install -qy git curl libmcrypt-dev mysql-client gnupg gnupg2 
          - yes | pecl install mcrypt-1.0.1
          - docker-php-ext-install pdo_mysql
          - bash ./install-composer.sh
          - composer install
          - curl -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh
          - bash nodesource_setup.sh
          - apt-get install nodejs -y
          - npm install
          - npm run prod
          - ln -f -s .env.pipelines .env
          - php artisan key:generate
          - php artisan migrate
          - php artisan serve &
          - sleep 5
          - ./vendor/bin/phpunit
          - curl -vk http://localhost:8000
        services:
          - mysql

definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'homestead'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'homestead'
        MYSQL_PASSWORD: 'secret'