image: phpunit/phpunit:6.5.3
pipelines:
  default:
  - step:
      caches:
      - composer
      script:
      - apk add --no-cache php7-gd php7-xmlwriter
      - php -r "file_exists('.env') || copy('.env.pipelines', '.env');"
      - composer install
      - php artisan key:generate
      - php artisan migrate --seed
      - vendor/bin/phpunit